services:
  messenger_server:
    build: .
    container_name: messenger_server
    ports:
      - "8765:8765"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=8765
